version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./setup_mariadb.sh:/docker-entrypoint-initdb.d/setup_mariadb.sh
      - ../TestDatabase:/TestDatabase
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: statiegeld_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
      
volumes:
  mariadb-data:
